2023-04-23:21:38:25,297, Starting web crawler...
2023-04-23:21:38:25,297, Crawling: https://www.wtatennis.com/
2023-04-23:21:38:25,297, Failed to crawl: https://www.wtatennis.com/
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 171, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 130, in crawl_url
    number_of_sites_crawled += 1
    ^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'number_of_sites_crawled' where it is not associated with a value
