2023-04-18:21:28:49,950, Starting web crawler...
2023-04-18:21:28:49,951, Crawling: https://www.espn.com/tennis/
2023-04-18:21:28:50,313, Finished crawling: https://www.espn.com/tennis/
2023-04-18:21:28:50,313, Crawling: #
2023-04-18:21:28:50,314, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,333, Crawling: #
2023-04-18:21:28:50,334, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,335, Crawling: #
2023-04-18:21:28:50,336, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,336, Crawling: #
2023-04-18:21:28:50,337, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,338, Crawling: #
2023-04-18:21:28:50,338, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,339, Crawling: #
2023-04-18:21:28:50,339, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,340, Crawling: #
2023-04-18:21:28:50,341, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,341, Crawling: http://preferences-mgr.truste.com/?type=espn&affiliateId=148
2023-04-18:21:28:50,485, Finished crawling: http://preferences-mgr.truste.com/?type=espn&affiliateId=148
2023-04-18:21:28:50,485, Crawling: http://www.espn.com/espn/apps/download?app=espn
2023-04-18:21:28:50,634, Finished crawling: http://www.espn.com/espn/apps/download?app=espn
2023-04-18:21:28:50,634, Crawling: #
2023-04-18:21:28:50,635, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,636, Crawling: #
2023-04-18:21:28:50,636, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,637, Crawling: http://www.espn.com/espn/apps/download?app=espn
2023-04-18:21:28:50,802, Finished crawling: http://www.espn.com/espn/apps/download?app=espn
2023-04-18:21:28:50,802, Crawling: #
2023-04-18:21:28:50,803, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,803, Crawling: #
2023-04-18:21:28:50,804, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,804, Crawling: http://www.espn.com/espn/mobile/products/products/_/id/17145860
2023-04-18:21:28:50,993, Finished crawling: http://www.espn.com/espn/mobile/products/products/_/id/17145860
2023-04-18:21:28:50,993, Crawling: #
2023-04-18:21:28:50,994, Failed to crawl: #
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#': No scheme supplied. Perhaps you meant https://#?
2023-04-18:21:28:50,995, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:52,743, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:52,743, Crawling: 
2023-04-18:21:28:52,744, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:28:52,745, Crawling: #
2023-04-18:21:28:52,745, Finished crawling: #
2023-04-18:21:28:52,745, Crawling: #main-content
2023-04-18:21:28:52,745, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:28:52,747, Crawling: #menu-menu-1
2023-04-18:21:28:52,747, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:28:52,748, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:53,948, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:53,948, Crawling: 
2023-04-18:21:28:53,949, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:28:53,949, Crawling: #main-content
2023-04-18:21:28:53,950, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:28:53,950, Crawling: #menu-menu-1
2023-04-18:21:28:53,950, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:28:53,951, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:55,121, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:55,121, Crawling: 
2023-04-18:21:28:55,121, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:28:55,122, Crawling: #main-content
2023-04-18:21:28:55,122, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:28:55,124, Crawling: #menu-menu-1
2023-04-18:21:28:55,124, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:28:55,125, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:56,412, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:56,412, Crawling: 
2023-04-18:21:28:56,412, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:28:56,413, Crawling: #main-content
2023-04-18:21:28:56,413, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:28:56,414, Crawling: #menu-menu-1
2023-04-18:21:28:56,414, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:28:56,415, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:57,780, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:57,780, Crawling: 
2023-04-18:21:28:57,780, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:28:57,781, Crawling: #main-content
2023-04-18:21:28:57,782, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:28:57,782, Crawling: #menu-menu-1
2023-04-18:21:28:57,783, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:28:57,783, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:59,077, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:28:59,077, Crawling: 
2023-04-18:21:28:59,077, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:28:59,078, Crawling: #main-content
2023-04-18:21:28:59,078, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:28:59,079, Crawling: #menu-menu-1
2023-04-18:21:28:59,079, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:28:59,080, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:00,305, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:00,305, Crawling: 
2023-04-18:21:29:00,306, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:29:00,307, Crawling: #main-content
2023-04-18:21:29:00,307, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:29:00,308, Crawling: #menu-menu-1
2023-04-18:21:29:00,308, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:29:00,309, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:01,427, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:01,427, Crawling: 
2023-04-18:21:29:01,427, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:29:01,428, Crawling: #main-content
2023-04-18:21:29:01,428, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:29:01,429, Crawling: #menu-menu-1
2023-04-18:21:29:01,429, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:29:01,430, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:02,963, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:02,963, Crawling: 
2023-04-18:21:29:02,963, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:29:02,964, Crawling: #main-content
2023-04-18:21:29:02,964, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:29:02,965, Crawling: #menu-menu-1
2023-04-18:21:29:02,965, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:29:02,966, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:03,989, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:03,990, Crawling: 
2023-04-18:21:29:03,990, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:29:03,991, Crawling: #main-content
2023-04-18:21:29:03,991, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:29:03,992, Crawling: #menu-menu-1
2023-04-18:21:29:03,992, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:29:03,992, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:05,430, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:05,430, Crawling: 
2023-04-18:21:29:05,431, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:29:05,432, Crawling: #main-content
2023-04-18:21:29:05,433, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:29:05,434, Crawling: #menu-menu-1
2023-04-18:21:29:05,435, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:29:05,436, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:06,647, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:06,647, Crawling: 
2023-04-18:21:29:06,648, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:29:06,649, Crawling: #main-content
2023-04-18:21:29:06,650, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:29:06,651, Crawling: #menu-menu-1
2023-04-18:21:29:06,651, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:29:06,652, Crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:08,406, Finished crawling: http://disneyprivacycenter.com/
2023-04-18:21:29:08,406, Crawling: 
2023-04-18:21:29:08,407, Failed to crawl: 
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2023-04-18:21:29:08,408, Crawling: #main-content
2023-04-18:21:29:08,408, Failed to crawl: #main-content
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#main-content': No scheme supplied. Perhaps you meant https://#main-content?
2023-04-18:21:29:08,408, Crawling: #menu-menu-1
2023-04-18:21:29:08,409, Failed to crawl: #menu-menu-1
Traceback (most recent call last):
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 105, in run_crawler
    self.crawl_url(url)
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 74, in crawl_url
    html = self.get_url_info(url)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sophiaho/CS262/Final-CS262/web_crawler.py", line 98, in get_url_info
    return requests.get(url).text
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '#menu-menu-1': No scheme supplied. Perhaps you meant https://#menu-menu-1?
2023-04-18:21:29:08,409, Crawling: http://disneyprivacycenter.com/
