2023-04-21:10:06:34,166, Starting web crawler...
2023-04-21:10:06:34,166, Crawling: https://www.wtatennis.com/
2023-04-21:10:06:34,567, Finished crawling: https://www.wtatennis.com/
2023-04-21:10:06:34,567, Crawling: apps
2023-04-21:10:06:34,567, Failed to crawl: apps
Traceback (most recent call last):
  File "web_crawler.py", line 151, in run_crawler
    self.crawl_url(url)
  File "web_crawler.py", line 112, in crawl_url
    html = self.get_url_info(url)
  File "web_crawler.py", line 142, in get_url_info
    return requests.get(url).text
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'apps': No schema supplied. Perhaps you meant http://apps?
2023-04-21:10:06:34,570, Crawling: http://instagram.com/wta
2023-04-21:10:06:35,764, Finished crawling: http://instagram.com/wta
2023-04-21:10:06:35,765, Crawling: http://www.usopenseries.com/home/default.sps
2023-04-21:10:06:35,927, Failed to crawl: http://www.usopenseries.com/home/default.sps
Traceback (most recent call last):
  File "web_crawler.py", line 151, in run_crawler
    self.crawl_url(url)
  File "web_crawler.py", line 114, in crawl_url
    player_count, date = self.get_player_info_and_date(html)
  File "web_crawler.py", line 84, in get_player_info_and_date
    if non_zero_arr:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-04-21:10:06:35,927, Crawling: http://www.youtube.com/user/wta
2023-04-21:10:06:36,443, Finished crawling: http://www.youtube.com/user/wta
2023-04-21:10:06:36,443, Crawling: https://join.whoop.com/WTA/=_blank
2023-04-21:10:06:36,664, Finished crawling: https://join.whoop.com/WTA/=_blank
2023-04-21:10:06:36,664, Crawling: https://open.spotify.com/show/7mO3pU6mfindpNSy5i2dlY
2023-04-21:10:06:37,049, Failed to crawl: https://open.spotify.com/show/7mO3pU6mfindpNSy5i2dlY
Traceback (most recent call last):
  File "web_crawler.py", line 151, in run_crawler
    self.crawl_url(url)
  File "web_crawler.py", line 114, in crawl_url
    player_count, date = self.get_player_info_and_date(html)
  File "web_crawler.py", line 84, in get_player_info_and_date
    if non_zero_arr:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2023-04-21:10:06:37,049, Crawling: https://open.spotify.com/show/7mO3pU6mfindpNSy5i2dlY
2023-04-21:10:06:37,049, Finished crawling: https://open.spotify.com/show/7mO3pU6mfindpNSy5i2dlY
2023-04-21:10:06:37,049, Crawling: https://podcasts.apple.com/us/podcast/wta-insider-podcast/id1052842829
